# Generated by Django 5.0 on 2023-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_dont_rely_on_paymentintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='stripe_id',
            field=models.CharField(max_length=128),
        ),
    ]
