# Generated by Django 2.1 on 2018-08-29 11:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
