# Generated by Django 2.1 on 2018-09-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
        ('events', '0003_move_subscriptions_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='archer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance_set', to='wallingford_castle.Archer'),
        ),
    ]
