# Generated by Django 2.0.1 on 2018-09-15 12:00

from django.db import migrations


def members_to_archers(apps, editor):
    Attendee = apps.get_model('events', 'Attendee')

    for attendee in Attendee.objects.all():
        attendee.archer = attendee.member.archer
        attendee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_build_events_from_sessions'),
        ('membership', '0013_fix_modified_fields'),
        ('wallingford_castle', '0014_build_events_from_sessions'),
    ]

    operations = [
        migrations.RunPython(members_to_archers),
    ]

