# Generated by Django 2.1 on 2018-09-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
        ('events', '0005_members_to_archers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='archer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance_set', to='wallingford_castle.Archer'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('archer', 'event')},
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='member',
        ),
    ]
