# Generated by Django 2.1.1 on 2018-11-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
        ('events', '0007_remove_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='archer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallingford_castle.Archer'),
        ),
    ]
