# Generated by Django 2.1.1 on 2018-11-13 19:48

from django.db import migrations


def populate_booking_archer(apps, schema):
    Booking = apps.get_model('events', 'Booking')

    for booking in Booking.objects.all():
        booking.archer = booking.member.archer
        booking.save(update_fields=['archer'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_booking_archer'),
    ]

    operations = [
        migrations.RunPython(populate_booking_archer),
    ]
