# Generated by Django 2.1.1 on 2018-11-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
        ('events', '0009_populate_booking_archer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='archer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallingford_castle.Archer'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('archer', 'event')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='member',
        ),
    ]
