# Generated by Django 2.2.1 on 2020-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
        ('events', '0010_booking_archer_non_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('target', models.PositiveIntegerField()),
                ('distance', models.CharField(blank=True, default='', max_length=100)),
                ('archers', models.ManyToManyField(to='wallingford_castle.Archer')),
            ],
        ),
    ]
