# Generated by Django 2.2.1 on 2020-07-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_booking_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedslot',
            unique_together={('start', 'target')},
        ),
    ]
