# Generated by Django 2.2.1 on 2020-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_add_uniqueness_of_target_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtemplate',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingtemplate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
