# Generated by Django 3.1.7 on 2021-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0015_coaching_subscription_fields'),
        ('events', '0016_add_group_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedslot',
            name='archers',
            field=models.ManyToManyField(blank=True, to='wallingford_castle.Archer'),
        ),
    ]
