# Generated by Django 3.2 on 2021-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_update_timzeones'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedslot',
            name='face',
            field=models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookingtemplate',
            name='ab_faces',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bookedslot',
            unique_together={('start', 'target', 'face')},
        ),
    ]
