# Generated by Django 3.2.12 on 2022-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_add_venue_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedslot',
            name='b_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingtemplate',
            name='b_targets',
            field=models.PositiveIntegerField(blank=True, help_text='Enables a split range', null=True),
        ),
    ]
