# Generated by Django 4.1 on 2022-09-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_add_venue_model'),
        ('events', '0021_split_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedslot',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingtemplate',
            unique_together={('date', 'venue')},
        ),
    ]
