# Generated by Django 4.1 on 2022-09-23 08:24

from django.db import migrations


def populate_slot_venue(apps, schema_editor):
    BookedSlot = apps.get_model('events', 'BookedSlot')
    BookingTemplate = apps.get_model('events', 'BookingTemplate')
    for slot in BookedSlot.objects.filter(venue__isnull=True):
        templates = BookingTemplate.objects.filter(date=slot.start.date())
        if len(templates) == 1:
            slot.venue = templates[0].venue
            slot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_split_venue_days'),
    ]

    operations = [
        migrations.RunPython(populate_slot_venue),
    ]
