# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_member_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='squad',
            field=models.BooleanField(default=False),
        ),
    ]
