# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_add_squad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='squad',
        ),
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('performance', 'Performance'), ('development', 'Development'), ('leisure', 'Leisure'), ('novice', 'Novice')], default='', max_length=20),
        ),
    ]
