# Generated by Django 2.0.1 on 2018-01-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_add_archer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('full', 'Full member'), ('concession', 'Concession member'), ('associate', 'Associate member'), ('non-shooting', 'Non-shooting member')], max_length=20),
        ),
    ]
