# Generated by Django 2.0.1 on 2018-08-13 10:32

from django.db import migrations


def migrate_to_archers(apps, editor):
    Member = apps.get_model('membership', 'Member')
    Archer = apps.get_model('wallingford_castle', 'Archer')

    for member in Member.objects.filter(archer__isnull=True).order_by('id'):
        archer = Archer.objects.create(
            user=member.user,
            name=member.name,
            age=member.age,
            date_of_birth=member.date_of_birth,
            agb_number=member.agb_number,
            address=member.address,
            contact_number=member.contact_number,
            created=member.created,
        )
        member.archer = archer
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0010_refine_member_archer_link'),
        ('membership', '0009_refine_member_archer_link'),
    ]

    operations = [
        migrations.RunPython(migrate_to_archers),
    ]
