# Generated by Django 2.1 on 2018-08-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_tidy_up_member_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='subscription_id',
        ),
    ]
