# Generated by Django 2.1 on 2018-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_move_subscriptions_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
