# Generated by Django 2.2.1 on 2020-10-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_fix_modified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='coaching_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
