# Generated by Django 5.2.5 on 2025-08-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_pricing_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='agb_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
