# Generated by Django 5.2.5 on 2025-10-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_agb_valid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='coaching_conversion',
        ),
        migrations.RemoveField(
            model_name='member',
            name='coaching_performance',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gym_supplement',
        ),
        migrations.AddField(
            model_name='member',
            name='coaching_individual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='junior_training',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('full', 'Full member'), ('concession', 'Concession member'), ('minis', 'Minis member')], max_length=20),
        ),
    ]
