# Generated by Django 5.2.5 on 2026-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='can_be_ukrs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='can_be_wrs',
            field=models.BooleanField(default=False),
        ),
    ]
