version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.0
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root:root@localhost/circle_test?sslmode=disable
      - image: cimg/postgres:16.1
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip install pipenv
            pipenv install --ignore-pipfile
          name: Install requirements
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Run flake8
          command: |
            source .venv/bin/activate
            flake8 .
      - run:
          name: Run isort
          command: |
            source .venv/bin/activate
            isort -c --df .
      - run:
          name: Test
          command: pipenv run python manage.py test

workflows:
  main:
    jobs:
      - build-and-test
