# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agb_number', models.CharField(max_length=50, verbose_name='Archery GB number')),
                ('club', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('gent', 'Gent'), ('lady', 'Lady')], max_length=50)),
                ('bowstyle', models.CharField(choices=[('recurve', 'Recurve'), ('compound', 'Compound')], max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='\n        Please include details of any accessibility requirements, other\n        bowstyles, junior or masters age categories etc.\n    ')),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
