# Generated by Django 2.0.1 on 2018-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_add_tournament_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required for junior archers.', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='drugs_consent',
            field=models.BooleanField(default=False, verbose_name='I consent to drugs testing as required under WRS rules.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='future_event_consent',
            field=models.BooleanField(default=False, verbose_name='Please contact me about future competitions at Wallingford Castle Archers'),
        ),
        migrations.AddField(
            model_name='entry',
            name='gdpr_consent',
            field=models.BooleanField(default=False, verbose_name='I consent that some of the information here provided will be shared with tournament organisers, scoring systems, other competitors and ArcheryGB. I also consent that I may be contacted with further details of the event via email.'),
        ),
    ]
