# Generated by Django 3.1.3 on 2020-12-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_update_entry_details_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='\n        Please include details of any accessibility requirements, session and\n        target face preferences, other bowstyles, junior or masters age\n        categories etc.\n    '),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='camping',
            field=models.TextField(blank=True, default=''),
        ),
    ]
