# Generated by Django 3.2 on 2021-05-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_add_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='old_rounds',
        ),
        migrations.AddField(
            model_name='entry',
            name='waiting_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='waiting_list_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
