# Generated by Django 3.2.12 on 2022-08-12 13:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archery', '0001_initial'),
        ('tournaments', '0008_results_linking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('date', models.DateField()),
                ('has_wrs', models.BooleanField(default=True)),
                ('bowstyles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('recurve', 'Recurve'), ('compound', 'Compound'), ('barebow', 'Barebow'), ('longbow', 'Longbow'), ('flatbow', 'American Flatbow')], max_length=30), size=None)),
                ('event_format', models.TextField()),
                ('judges', models.TextField()),
                ('awards', models.TextField()),
                ('tournament_organiser', models.CharField(max_length=200)),
                ('tournament_organiser_email', models.EmailField(max_length=254)),
                ('dress', models.TextField()),
                ('drug_testing', models.TextField()),
                ('timing', models.TextField()),
                ('venue_description', models.TextField()),
                ('venue_google_search', models.CharField(max_length=200)),
                ('refreshments', models.TextField()),
                ('camping', models.TextField(blank=True, default='')),
                ('entry_information', models.TextField()),
                ('entry_fee', models.IntegerField()),
                ('entries_open', models.DateTimeField()),
                ('entries_close', models.DateTimeField()),
                ('waiting_list_enabled', models.BooleanField(default=False)),
                ('rounds', models.ManyToManyField(to='archery.Round')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.series'),
        ),
    ]
