# Generated by Django 4.1.7 on 2023-03-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_series_entries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='gender',
            field=models.CharField(choices=[('gent', 'Men'), ('lady', 'Women')], max_length=50),
        ),
    ]
