# Generated by Django 5.2.5 on 2026-01-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_update_gender_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='has_wrs',
            new_name='has_rs',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='has_wrs',
            new_name='has_rs',
        ),
    ]
