# Generated by Django 5.0 on 2023-12-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_update_gender_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='has_ukrs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='indoors',
            field=models.BooleanField(default=False, help_text='Displays indoor image.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='has_ukrs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='indoors',
            field=models.BooleanField(default=False, help_text='Displays indoor image.'),
        ),
    ]
