# Generated by Django 3.2 on 2021-09-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallingford_castle', '0017_add_coaching_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_group', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_day', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('session_start_time', models.TimeField()),
                ('coaches', models.ManyToManyField(related_name='coached_groups', to='wallingford_castle.Archer')),
                ('level', models.ManyToManyField(to='coaching.TrainingGroupType')),
                ('participants', models.ManyToManyField(related_name='training_groups', to='wallingford_castle.Archer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallingford_castle.season')),
            ],
        ),
    ]
