# Generated by Django 3.2 on 2021-12-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0017_add_coaching_groups'),
        ('coaching', '0001_add_coaching_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggrouptype',
            name='trial_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_1', models.DateTimeField()),
                ('session_2', models.DateTimeField()),
                ('session_3', models.DateTimeField()),
                ('session_4', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallingford_castle.archer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.traininggroup')),
            ],
        ),
    ]
