# Generated by Django 3.2.10 on 2021-12-16 10:09

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_add_venue_model'),
        ('venues', '0001_add_venue_model'),
        ('coaching', '0002_trials'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='session_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue'),
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('cancelled_because', models.TextField(blank=True, default='')),
                ('booked_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.bookedslot')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.traininggroup')),
            ],
            options={
                'unique_together': {('group', 'start')},
            },
        ),
    ]
