# Generated by Django 3.2.12 on 2022-03-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_add_venue_model'),
        ('coaching', '0003_coaching_group_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venues.venue'),
        ),
    ]
