# Generated by Django 3.2.12 on 2022-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_venue_not_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='b_range',
            field=models.BooleanField(default=False),
        ),
    ]
