# Generated by Django 4.1 on 2022-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_b_range_for_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='number_of_targets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='target',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
