# Generated by Django 4.1 on 2023-02-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0017_add_coaching_groups'),
        ('coaching', '0008_season_planning'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archerseason',
            unique_together={('archer', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='archertrack',
            unique_together={('track', 'archer_season')},
        ),
        migrations.AlterUniqueTogether(
            name='competitivetrack',
            unique_together={('season', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('date', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'archer_season')},
        ),
    ]
