# Generated by Django 4.1 on 2023-02-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0009_uniqueness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tournament_id',
            new_name='tournament',
        ),
    ]
