# Generated by Django 4.1 on 2023-02-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0010_rename_event_id_event_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='wants_transport',
            field=models.CharField(blank=True, choices=[('required', 'I can only attend if transport is offered'), ('interested', 'Transport for archer would be helpful but we could make our own way there'), ('plus-parent', 'Transport for archer and a parent would be helpful but we could make our own way there'), ('own-way', 'We will make our own way there')], max_length=20, null=True),
        ),
    ]
