# Generated by Django 5.0 on 2025-03-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0012_scayt'),
        ('wallingford_castle', '0017_add_coaching_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='training_groups', to='wallingford_castle.archer'),
        ),
    ]
