# Generated by Django 5.2.5 on 2026-09-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0013_empty_groups'),
        ('venues', '0001_add_venue_model'),
        ('wallingford_castle', '0019_student_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_ones_shooting', to='wallingford_castle.archer')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_ones_coaching', to='wallingford_castle.archer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
            options={
                'verbose_name': '1:1 session',
                'verbose_name_plural': '1:1 sessions',
            },
        ),
    ]
