# Generated by Django 5.2.5 on 2026-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0014_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoone',
            name='session_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
