# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0003_auto_20160131_1738'),
    ]

    database_operations = [
        migrations.AlterModelTable('BeginnersCourseInterest', 'beginners_beginner')
    ]

    state_operations = [
        migrations.DeleteModel('BeginnersCourseInterest')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
