# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0004_delete_beginnerscourseinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournament_only',
            field=models.BooleanField(default=False),
        ),
    ]
