# Generated by Django 2.0.1 on 2018-01-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0007_update_membership_types'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE wallingford_castle_membershipinterest SET membership_type='concession'
            WHERE membership_type='student' OR (membership_type='full' AND age='junior')
        ''')
    ]
