# Generated by Django 2.0.1 on 2018-08-12 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0008_modernise_membership_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('agb_number', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.TextField(default='')),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('managing_users', models.ManyToManyField(blank=True, related_name='managed_archers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
