# Generated by Django 2.1 on 2018-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0010_refine_member_archer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
