# Generated by Django 2.1 on 2018-09-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0012_fix_modified_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
