# Generated by Django 2.1 on 2018-09-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0013_address_not_required_for_some_archers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archers', to=settings.AUTH_USER_MODEL),
        ),
    ]
