# Generated by Django 2.2.1 on 2020-10-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipinterest',
            name='coaching_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
