# Generated by Django 3.2 on 2021-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0015_coaching_subscription_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
