# Generated by Django 4.1.7 on 2023-10-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0017_add_coaching_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='collection_alternatives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='archer',
            name='collection_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archer',
            name='medical_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='archer',
            name='photography_coaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archer',
            name='photography_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archer',
            name='primary_contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='archer',
            name='secondary_contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='archer',
            name='secondary_contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
