# Generated by Django 5.2.5 on 2025-10-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0017_add_coaching_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipinterest',
            name='membership_type',
            field=models.CharField(choices=[('full', 'Full member'), ('concession', 'Concession member'), ('minis', 'Minis member')], max_length=20),
        ),
    ]
