# Generated by Django 5.2.5 on 2026-09-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0018_new_performance_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipinterest',
            name='membership_type',
            field=models.CharField(choices=[('full', 'Full member'), ('concession', 'Concession member'), ('minis', 'Minis member'), ('student', 'Student member')], max_length=20),
        ),
    ]
