# Generated by Django 2.0.1 on 2018-06-28 12:43

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summer2018Signup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=255)),
                ('student_date_of_birth', models.DateField()),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('group', models.CharField(max_length=30)),
                ('experience', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('contact_consent', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
