# Generated by Django 2.0.1 on 2018-08-12 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0009_courses_restructure'),
        ('courses', '0002_add_summer_2018_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('experience', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('communication_notes', models.TextField(blank=True, default='')),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('contact', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_id', models.CharField(blank=True, default='', max_length=32)),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallingford_castle.Archer')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('can_book_individual_sessions', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0, 5400))),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
