# Generated by Django 2.0.1 on 2018-08-29 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='members_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='members_price_per_session',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='open_for_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='open_to_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='open_to_non_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_per_session',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
