# Generated by Django 2.1 on 2018-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_members_flag_remove_unneeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
