# Generated by Django 2.1 on 2018-09-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_build_events_from_sessions'),
        ('courses', '0008_add_course_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event'),
        ),
    ]
