# Generated by Django 2.1.1 on 2018-09-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
        ('courses', '0011_remove_old_course_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='summer2018signup',
            name='archer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallingford_castle.Archer'),
        ),
    ]
