# Generated by Django 2.1.1 on 2018-09-18 13:24

from django.db import migrations


def migrate_to_archers(apps, editor):
    Summer2018Signup = apps.get_model('courses', 'Summer2018Signup')
    Archer = apps.get_model('wallingford_castle', 'Archer')
    User = apps.get_model('wallingford_castle', 'User')

    for signup in Summer2018Signup.objects.all():
        user, created = User.objects.get_or_create(
            email=signup.email,
            defaults={
                'is_active': False,
            }
        )
        archer, _ = Archer.objects.get_or_create(
            name=signup.student_name,
            user=user,
            defaults={
                'date_of_birth': signup.student_date_of_birth,
                'age': 'junior',
                'contact_number': signup.contact_number,
            }
        )
        signup.archer = archer
        signup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_link_summer_to_archers'),
        ('wallingford_castle', '0014_build_events_from_sessions'),
    ]

    operations = [
        migrations.RunPython(migrate_to_archers),
    ]
