# Generated by Django 2.1.1 on 2019-03-16 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_session_coaching_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Attendee')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='public_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attendeesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Session'),
        ),
    ]
