# Generated by Django 3.1.7 on 2021-04-14 12:39

from django.conf import settings
from django.db import migrations


def migrate_times(apps, editor):
    Session = apps.get_model('courses', 'Session')
    for session in Session.objects.all():
        session.start_time = session.start_time.replace(tzinfo=None).replace(tzinfo=settings.TZ)
        session.save(update_fields=['start_time'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_add_booked_slots'),
    ]

    operations = [
        migrations.RunPython(migrate_times, migrations.RunPython.noop),
    ]
