# Generated by Django 2.1.1 on 2018-09-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallingford_castle', '0014_build_events_from_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_awarded', models.DateField(blank=True, null=True)),
                ('badge', models.CharField(choices=[('red-feather', 'Red Feather'), ('gold-feather', 'Gold Feather'), ('white-arrow', 'White Arrow'), ('black-arrow', 'Black Arrow'), ('blue-arrow', 'Blue Arrow')], max_length=31)),
                ('badge_group', models.CharField(choices=[('wa-beginners', 'WA beginners')], max_length=31)),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallingford_castle.Archer')),
            ],
        ),
    ]
