# Generated by Django 2.1.1 on 2018-10-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_new_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
