# Generated by Django 2.1.1 on 2019-04-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_add_outdoor_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_group',
            field=models.CharField(choices=[('wa-beginners', 'WA beginners'), ('half-portsmouth', 'Half Portsmouth'), ('half-wa-18', 'Half WA 18'), ('outdoor-250-award', 'Outdoor 250 Award')], max_length=31),
        ),
    ]
