# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 19:40
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beginners', '0001_initial'),
        ('wallingford_castle', '0004_delete_beginnerscourseinterest'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Beginner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name='beginner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beginners.BeginnersCourse'),
        ),
        migrations.AddField(
            model_name='beginner',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beginner',
            name='communication_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='beginner',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for a course'), ('not-interested', 'No longer interested'), ('on-course', 'Allocated a course'), ('joined', 'Completed course and joined the club'), ('left', 'Completed course but did not join')], default='waiting', max_length=20),
        ),
    ]
