# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beginners', '0002_add_beginner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beginnerscourse',
            options={'ordering': ('-counter',)},
        ),
        migrations.AlterField(
            model_name='beginnerscourse',
            name='counter',
            field=models.PositiveIntegerField(unique=True, verbose_name='Beginners course #'),
        ),
    ]
