# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beginners', '0004_paying_for_beginners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginner',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for a course'), ('not-interested', 'No longer interested'), ('on-course', 'Allocated a course'), ('fast-track', 'Arranged a fast track course'), ('joined', 'Completed course and joined the club'), ('left', 'Completed course but did not join')], default='waiting', max_length=20),
        ),
    ]
