# Generated by Django 2.1 on 2018-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beginners', '0005_add_archer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginner',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='beginnerscourse',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='beginnerscoursesession',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
