# Generated by Django 2.2.1 on 2020-07-16 08:31

from django.db import migrations

STATUS_WAITING = 'waiting'
STATUS_NOT_INTERESTED = 'not-interested'
STATUS_ON_COURSE = 'on-course'
STATUS_FAST_TRACK = 'fast-track'
STATUS_JOINED = 'joined'
STATUS_LEFT = 'left'

def set_2015_fee(apps, schema_editor):
    Beginner = apps.get_model('beginners', 'Beginner')
    for beginner in Beginner.objects.all():
        if beginner.status == STATUS_FAST_TRACK:
            if beginner.age == 'junior':
                beginner.fee = 60
            else:
                beginner.fee = 100
        elif beginner.status in [STATUS_ON_COURSE, STATUS_JOINED, STATUS_LEFT, STATUS_NOT_INTERESTED]:
            if beginner.age == 'junior':
                beginner.fee = 30
            else:
                beginner.fee = 50
        elif beginner.status == STATUS_WAITING:
            if beginner.age == 'junior':
                beginner.fee = 50
            else:
                beginner.fee = 80
        beginner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('beginners', '0007_add_fee_field'),
    ]

    operations = [
        migrations.RunPython(
            set_2015_fee,
            migrations.RunPython.noop,
        )
    ]
