# Generated by Django 3.1.7 on 2021-04-14 12:29

from django.conf import settings
from django.db import migrations


def migrate_times(apps, editor):
    BeginnersCourseSession = apps.get_model('beginners', 'BeginnersCourseSession')
    for session in BeginnersCourseSession.objects.all():
        session.start_time = session.start_time.replace(tzinfo=None).replace(tzinfo=settings.TZ)
        session.save(update_fields=['start_time'])


class Migration(migrations.Migration):

    dependencies = [
        ('beginners', '0008_set_correct_fee'),
    ]

    operations = [
        migrations.RunPython(migrate_times, migrations.RunPython.noop),
    ]
