# Generated by Django 3.2.12 on 2022-04-08 13:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beginners', '0009_update_timzeones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnerscoursesession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
