# Generated by Django 4.1 on 2022-09-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_add_venue_model'),
        ('beginners', '0010_beginners_default_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerscourse',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='beginner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beginners.beginnerscourse'),
        ),
    ]
